#!/bin/bash

## Description: Run NODE_OPTIONS=--inspect=0.0.0.0:9229 ./node_modules/.bin/vite dev in the web container
## Usage: viteinspect
## Example: "ddev viteinspect"
## ExecRaw: true

NODE_OPTIONS=--inspect=0.0.0.0:9229 ./node_modules/.bin/vite dev